"""
Django settings for sistema_fidelizacao project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# from pickle import FALSE

import importlib
import os
from pathlib import Path

from decouple import Csv, config
from django.contrib.messages import constants as messages

# ===========================================
# CONFIGURAÇÕES DE SEGURANÇA
# ===========================================
try:
    import importlib

    importlib.util.find_spec("security_config")

    SECURITY_ENABLED = True
except (ImportError, AttributeError):
    SECURITY_ENABLED = False


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-change-me-in-production",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = [
    *config(
        "ALLOWED_HOSTS",
        default="fidelizamax.app.br,www.fidelizamax.app.br,localhost,127.0.0.1",
        cast=Csv(),
    ),
    "testserver",
]

# CSRF trusted origins
# In production, read from env. In development, also allow local hosts over HTTP.
CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    default="https://fidelizamax.app.br,https://www.fidelizamax.app.br",
    cast=Csv(),
)

if DEBUG:
    CSRF_TRUSTED_ORIGINS += [
        "http://192.168.18.158",
        "http://localhost",
        "http://127.0.0.1",
    ]

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# Ou 'django.core.mail.backends.filebased.EmailBackend' com
# EMAIL_FILE_PATH = '/tmp/app-messages'

# Application definition

MESSAGE_TAGS = {
    messages.DEBUG: "alert-secondary",
    messages.INFO: "alert-info",
    messages.SUCCESS: "alert-success",
    messages.WARNING: "alert-warning",
    messages.ERROR: "alert-danger",
}

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "geografia",
    "colaboradores",
    "convidados",
    "user_profiles",
    "mensagens",
    "recepcao",
    "historico",
    "django_filters",
    "channels",
    # "chat",  # desabilitado temporariamente
    "django_ratelimit",
    "django_otp",
    "django_otp.plugins.otp_totp",
    "django_otp.plugins.otp_static",
    "django_extensions",
    "crispy_forms",
    "crispy_bootstrap5",
]

# Carrega app 'security' somente em produção (quando existir)
ENVIRONMENT = config("ENVIRONMENT", default="development")
try:
    if ENVIRONMENT == "production" and importlib.util.find_spec("security") is not None:
        INSTALLED_APPS.append("security")
except Exception:
    pass

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Tracking de atividade e idle timeout por usuário
    "user_profiles.middleware.UserActivityMiddleware",
    # Middleware de segurança - DESABILITADO PARA DEBUG
    # "django_otp.middleware.OTPMiddleware",
    # "security.frontend_protection.FrontendProtectionMiddleware",
    # "security.headers_protection.HeadersProtectionMiddleware",
    "django_ratelimit.middleware.RatelimitMiddleware",
]

ROOT_URLCONF = "sistema_fidelizacao.urls"

# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) #

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "sistema_fidelizacao.context_processors.debug_flag",
                "sistema_fidelizacao.context_processors.user_badges",
            ],
            # 'loaders': [
            #     'django.template.loaders.filesystem.Loader',
            #     # Busca nos diretórios listados em DIRS
            #     'django.template.loaders.app_directories.Loader',
            # ]
        },
    },
]

WSGI_APPLICATION = "sistema_fidelizacao.wsgi.application"

ASGI_APPLICATION = "sistema_fidelizacao.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": config("DB_ENGINE", default="django.db.backends.postgresql"),
        "NAME": config("DB_NAME", default="sisvot_db"),
        "USER": config("DB_USER", default="sisuserdb"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST", default="127.0.0.1"),
        "PORT": config("DB_PORT", default="5432"),
    }
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
        # "BACKEND": "channels_redis.core.RedisChannelLayer",
        # "CONFIG": {
        # "hosts": [("localhost", 6379)],
        # },
    },
}

# ===========================================
# CONFIGURAÇÕES DE CACHE
# ===========================================
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    },
    "rate_limit": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "rate-limit-cache",
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/Cuiaba"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
STATICFILES_STORAGE = "whitenoise.storage.StaticFilesStorage"

# Configurações adicionais do WhiteNoise
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True
WHITENOISE_ROOT = os.path.join(BASE_DIR, "staticfiles")
WHITENOISE_INDEX_FILE = True
WHITENOISE_MIMETYPES = {
    ".js": "application/javascript",
    ".css": "text/css",
    ".html": "text/html",
}

# Uploads (fotos e anexos)
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Configuração de upload de arquivos
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = "/login/"

LOGIN_REDIRECT_URL = "home"

LOGOUT_REDIRECT_URL = "/login/"

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# SECURE_SSL_REDIRECT = True


# === CONFIGURAÇÃO CONTENT SECURITY POLICY (CSP) PARA django-csp >= 4.0 ===
# Certifique-se de que todas as configurações antigas CSP_xxx_SRC foram
# removidas ou comentadas.

CSP_DEFAULT_SRC = ("'self'", "https://unpkg.com", "https://*.tile.openstreetmap.org")
CSP_SCRIPT_SRC = (
    "'self'",
    "'unsafe-inline'",
    "https://unpkg.com",
    "https://code.jquery.com",
    "https://cdnjs.cloudflare.com",
    "https://cdn.jsdelivr.net",
)
CSP_STYLE_SRC = (
    "'self'",
    "'unsafe-inline'",
    "https://unpkg.com",
    "https://cdn.jsdelivr.net",
)
CSP_IMG_SRC = ("'self'", "data:", "https://*.tile.openstreetmap.org")
CSP_FONT_SRC = ("'self'", "https://cdn.jsdelivr.net")
CSP_CONNECT_SRC = ("'self'",)

# Se você está usando DEBUG=True, pode definir CSP_REPORT_ONLY = False
# para ver os bloqueios no console.
# Em produção, você usaria CSP_REPORT_ONLY = True com um URL para onde
# os relatórios seriam enviados.
# Por agora, mantenha-o em False para que as políticas sejam aplicadas.
CSP_REPORT_ONLY = False

# Para desenvolvimento, se você tiver problemas persistentes com
# "unsafe-inline" ou "unsafe-eval"
# E *APENAS* EM DESENVOLVIMENTO:
# CSP_SCRIPT_SRC += ("'unsafe-eval'",) # Se precisar para alguns scripts que usam eval
# CSP_STYLE_SRC += ("'unsafe-inline'",) # Já incluído acima

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# Ou outro backend (console para teste)
EMAIL_HOST = config("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
# EMAIL_USE_SSL = False
# Se usar SSL (porta 465), defina como True e EMAIL_USE_TLS como False
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="lucianolrv@gmail.com")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = "suporte@fidelizamax.app.br"  # E-mail que aparecerá como remetente
SERVER_EMAIL = "suporte@fidelizamax.app.br"  # E-mail para erros de servidor

# Configuração para o e-mail de reset de senha
# Nome do site que aparece no e-mail (opcional)
SITE_NAME = "SisAps - Fidelização de Apoiadores"
# Domínio completo que aparecerá no link de reset de senha
# É CRÍTICO que este seja o seu domínio de produção, ex:
# https://cadastro.fidelizamax.app.br
# Use "SITE_ID = 1" e o objeto Site do Django para gerenciar isso
# dinamicamente se tiver vários domínios.
# Ou defina na mão se for um único domínio fixo:
DOMAIN_NAME = "fidelizamax.app.br"

# ===========================================
# CONFIGURAÇÕES DO CRISPY FORMS
# ===========================================
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# ===========================================
# Sessões: idle timeout e expiração
# ===========================================
SESSION_COOKIE_AGE = 60 * 60 * 8  # 8 horas (tempo máximo de sessão)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
# Idle timeout (auto-logout por inatividade)
IDLE_TIMEOUT_SECONDS = 30 * 60  # 30 minutos

# ===========================================
# CONFIGURAÇÕES DE SEGURANÇA PARA PRODUÇÃO
# ===========================================
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = "DENY"

    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = "Lax"

    print("✅ Configurações de segurança aplicadas para produção")
else:
    print("⚠️  Ambiente de desenvolvimento - configurações de segurança reduzidas")

# ===========================================
# CONFIGURAÇÕES DE RATE LIMITING PARA MENSAGENS
# ===========================================
MAX_MESSAGES_PER_MINUTE = config("MAX_MESSAGES_PER_MINUTE", default=10, cast=int)
MAX_MESSAGES_PER_HOUR = config("MAX_MESSAGES_PER_HOUR", default=100, cast=int)

# ===========================================
# CONFIGURAÇÕES DE RATE LIMITING PARA LOGIN
# ===========================================
RATELIMIT_ENABLE = True
RATELIMIT_USE_CACHE = "rate_limit"

# ===========================================
# CONFIGURAÇÕES WHATSAPP CLOUD API (META)
# ===========================================
WHATSAPP_PHONE_NUMBER_ID = config("WHATSAPP_PHONE_NUMBER_ID", default="")
WHATSAPP_ACCESS_TOKEN = config("WHATSAPP_ACCESS_TOKEN", default="")
WHATSAPP_BUSINESS_ACCOUNT_ID = config("WHATSAPP_BUSINESS_ACCOUNT_ID", default="")
USAR_WHATSAPP_CLOUD_API = config("USAR_WHATSAPP_CLOUD_API", default=False, cast=bool)
