# Generated by Django 5.2.4 on 2025-09-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "0002_colaborador_cadastrado_por"),
    ]

    operations = [
        migrations.AddField(
            model_name="colaborador",
            name="data_nascimento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
