# Generated by Django 5.2.4 on 2026-02-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "0003_colaborador_data_nascimento"),
    ]

    operations = [
        migrations.AddField(
            model_name="colaborador",
            name="tipo",
            field=models.CharField(
                choices=[("colaborador", "Colaborador"), ("acs_ace", "ACS/ACE")],
                default="colaborador",
                max_length=20,
            ),
        ),
    ]
