# Generated by Django 5.2.4 on 2026-05-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "0004_colaborador_tipo"),
    ]

    operations = [
        # Criar a nova tabela TipoColaborador
        migrations.CreateModel(
            name="TipoColaborador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("ativo", models.BooleanField(default=True)),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tipos_colaborador",
                "verbose_name": "Tipo de Colaborador",
                "verbose_name_plural": "Tipos de Colaborador",
                "ordering": ["nome"],
            },
        ),
        # Inserir os tipos existentes
        migrations.RunSQL(
            """
            INSERT INTO tipos_colaborador (nome, descricao, ativo, data_cadastro)
            VALUES
                ('Colaborador', 'Colaborador padrão do sistema', true, NOW()),
                ('ACS/ACE', 'Agente Comunitário de Saúde/Agente Comunitário de Endemias', true, NOW())
            ON CONFLICT (nome) DO NOTHING;
            """,
            reverse_sql="""
            DELETE FROM tipos_colaborador WHERE nome IN ('Colaborador', 'ACS/ACE');
            """,
        ),
        # Adicionar uma nova coluna tipo_temp (BigInteger para armazenar IDs)
        migrations.AddField(
            model_name="colaborador",
            name="tipo_temp",
            field=models.BigIntegerField(null=True),
        ),
        # Migrar os dados existentes para a nova coluna
        migrations.RunSQL(
            """
            UPDATE colaboradores
            SET tipo_temp = (
                CASE LOWER(tipo)
                    WHEN 'colaborador' THEN (SELECT id FROM tipos_colaborador WHERE nome = 'Colaborador' LIMIT 1)
                    WHEN 'acs_ace' THEN (SELECT id FROM tipos_colaborador WHERE nome = 'ACS/ACE' LIMIT 1)
                    ELSE (SELECT id FROM tipos_colaborador WHERE nome = 'Colaborador' LIMIT 1)
                END
            );
            """,
            reverse_sql="""
            UPDATE colaboradores
            SET tipo = (
                CASE
                    WHEN tipo_temp = (SELECT id FROM tipos_colaborador WHERE nome = 'Colaborador' LIMIT 1) THEN 'colaborador'
                    WHEN tipo_temp = (SELECT id FROM tipos_colaborador WHERE nome = 'ACS/ACE' LIMIT 1) THEN 'acs_ace'
                    ELSE 'colaborador'
                END
            );
            """,
        ),
        # Remover o campo tipo antigo
        migrations.RemoveField(
            model_name="colaborador",
            name="tipo",
        ),
        # Renomear tipo_temp para tipo
        migrations.RenameField(
            model_name="colaborador",
            old_name="tipo_temp",
            new_name="tipo",
        ),
        # Alterar o campo tipo para ForeignKey com as propriedades corretas
        migrations.AlterField(
            model_name="colaborador",
            name="tipo",
            field=models.ForeignKey(
                "colaboradores.TipoColaborador",
                on_delete=models.PROTECT,
                related_name="colaboradores",
                verbose_name="Tipo",
            ),
        ),
    ]
