# Generated by Django 5.2.4 on 2026-05-13 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "0005_create_tipo_colaborador_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colaborador",
            name="tipo",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="colaboradores",
                to="colaboradores.tipocolaborador",
                verbose_name="Tipo",
            ),
        ),
    ]
