# Generated by Django 5.2.4 on 2026-05-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "0006_alter_colaborador_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipocolaborador",
            name="cor",
            field=models.CharField(
                choices=[
                    ("success", "Verde"),
                    ("primary", "Azul"),
                    ("danger", "Vermelho"),
                    ("warning", "Amarelo"),
                    ("info", "Azul Claro"),
                    ("secondary", "Cinza"),
                    ("dark", "Preto"),
                    ("purple", "Roxo"),
                ],
                default="success",
                max_length=20,
            ),
        ),
    ]
