# Generated by Django 5.2.4 on 2026-05-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "0007_tipocolaborador_cor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tipocolaborador",
            name="cor",
            field=models.CharField(
                choices=[
                    ("success", "Verde"),
                    ("primary", "Azul"),
                    ("danger", "Vermelho"),
                    ("warning", "Amarelo"),
                    ("info", "Azul Claro"),
                    ("secondary", "Cinza"),
                    ("dark", "Preto"),
                    ("purple", "Roxo"),
                    ("pink", "Rosa"),
                    ("orange", "Laranja"),
                    ("teal", "Verde Azulado"),
                    ("cyan", "Ciano"),
                    ("indigo", "Índigo"),
                    ("brown", "Marrom"),
                    ("lime", "Lima"),
                    ("coral", "Coral"),
                    ("navy", "Marinho"),
                    ("olive", "Oliva"),
                ],
                default="success",
                max_length=20,
            ),
        ),
    ]
