-- Script SQL para inserir TODOS os bairros de Várzea Grande - MT
-- Execute este script no banco de dados PostgreSQL

-- Primeiro, verificar se a cidade Várzea Grande existe:
-- SELECT id, nome_cidade FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande';

-- Bairros de Várzea Grande - MT:
INSERT INTO bairros (nome_bairro, cidade_id) VALUES
('7 De Maio', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('24 De Dezembro', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Água Limpa', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Água Vermelha', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Alameda', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Alto da Boa Vista', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Asa Bela', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Bonsucesso (Distrito)', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Centro', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Centro Norte', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Centro Sul', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Carrapicho', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Cabo Michel', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Capão do Pequi', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Capão Grande', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Capela do Piçarrão', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Cidade de Deus', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Cohab Asa Branca', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Cohab Canelas', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Cohab Cristo Rei', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Cohab Dom Orlando Chaves', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Cohab Jaime Campos', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Cohab João Baracat', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Cohab Jardim Primavera', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Canelas', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Colinas Verdejantes', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Construmat', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Costa Verde', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Dom Diego', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Distrito Industrial', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Domingos Sávio', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Engordador (Distrito)', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Figueirinha', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Frutal de Minas', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Glória', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Hélio Ponce', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Industrial I', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Industrial II', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Industrial III', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Industrial IV', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim Alá', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim América', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim Buenos Aires', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim Cerrado', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim Costa Verde', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim Campos Verdes', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim das Oliveiras', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim dos Estados', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim ElDourado', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim Esmeralda', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim Glória I', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim Glória II', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim Imperador', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim Icaraí', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim Imperial', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim Itororó', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim Ipanema', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim Manaíra', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim Kataguás', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim Manancial', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim Marajoara', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim Marajoara II', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim Mariana', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim Novo Horizonte', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim Novo Mundo', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim Ouro Verde', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim Panorama', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim Paula I', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim Paula II', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim Potiguar', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim União', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim Rodrigues', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim Vista Alegre', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jardim Vitória Régia', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Jeani', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Lagoa do Jacaré', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Limpo Grande (Distrito)', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Loteamento Joaquim Curvo', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Loteamento Parque do Jatobá', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Marajoara', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Mapim', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Maringá I', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Maringá II', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Maringá III', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Monte Castelo', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Nair Sacre', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Nova Esperança', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Nova Fronteira', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Novo Mato Grosso', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Nova Várzea Grande', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Novo Mundo', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Nossa Senhora da Guia', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Ouro Branco', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Ouro Verde', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Pai André (Distrito)', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Pampulha', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Panamericano', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Parque Del Rei', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Parque Atlântico', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Parque do Lago', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Parque Mangabeiras', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Parque Sabiá', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Parque São João', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Parque Cabo Michel', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Paiaguás', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Pirinéu', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Planalto Ipiranga', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Planalto Beira Rio', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Ponte Nova', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Portal da Amazônia', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Praia Grande (Distrito)', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Princesa do Sol', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Residencial Jacarandá', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Residencial Santa Clara', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Residencial São Francisco', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Santa Izabel', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('São Benedito', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Santa Luzia', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Santa Maria I', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Santa Maria II', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('São Marcos', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('São Mateus', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('São Mateus II', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('São Simão', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Serra Dourada', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Souza Lima (Distrito)', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Treze de Setembro', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Terra Nova', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Unipark', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Vila Artur', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Vila Operária', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Vila São João', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Vinte e três de Setembro', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Vitória Régia', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1)),
('Vila Ipase', (SELECT id FROM cidades WHERE nome_cidade ILIKE 'Várzea Grande' LIMIT 1));
