# Generated by Django 5.2.4 on 2026-05-20 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mensagens", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CampanhaMensagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("filtros_usados", models.JSONField(blank=True, default=dict)),
                (
                    "tipo_mensagem",
                    models.CharField(
                        choices=[("sms", "SMS"), ("whatsapp", "WhatsApp")],
                        max_length=10,
                    ),
                ),
                ("conteudo", models.TextField()),
                (
                    "template_usado",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("total_destinatarios", models.IntegerField(default=0)),
                ("total_enviadas", models.IntegerField(default=0)),
                ("total_falhas", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("enviando", "Enviando"),
                            ("concluido", "Concluído"),
                            ("parcial", "Parcial"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Campanha de Mensagem",
                "verbose_name_plural": "Campanhas de Mensagens",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Mensagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destinatario_nome", models.CharField(max_length=200)),
                ("destinatario_telefone", models.CharField(max_length=20)),
                ("destinatario_tipo", models.CharField(max_length=20)),
                ("destinatario_id", models.PositiveIntegerField()),
                (
                    "tipo_mensagem",
                    models.CharField(
                        choices=[("sms", "SMS"), ("whatsapp", "WhatsApp")],
                        max_length=10,
                    ),
                ),
                ("conteudo", models.TextField()),
                (
                    "template_usado",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("enviada", "Enviada"),
                            ("falhou", "Falhou"),
                        ],
                        default="pendente",
                        max_length=10,
                    ),
                ),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
                ("data_processamento", models.DateTimeField(blank=True, null=True)),
                ("erro_detalhes", models.TextField(blank=True, null=True)),
                (
                    "api_message_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("api_response", models.JSONField(blank=True, null=True)),
                (
                    "campanha",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensagens",
                        to="mensagens.campanhamensagem",
                    ),
                ),
                (
                    "enviado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem",
                "verbose_name_plural": "Mensagens",
                "ordering": ["-data_envio"],
            },
        ),
    ]
