# Generated by Django 5.2.4 on 2026-05-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mensagens", "0002_campanhamensagem_mensagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatemensagem",
            name="imagem",
            field=models.URLField(blank=True, default=""),
        ),
    ]
