# Generated by Django 5.2.4 on 2026-05-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mensagens", "0003_templatemensagem_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatemensagem",
            name="meta_template_language",
            field=models.CharField(blank=True, default="pt_BR", max_length=10),
        ),
        migrations.AddField(
            model_name="templatemensagem",
            name="meta_template_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nome do template aprovado no Meta Business (ex: promocao_maio). Deixe vazio para enviar como texto livre.",
                max_length=100,
            ),
        ),
    ]
