# Generated by Django 5.2.4 on 2025-09-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
