# Generated by Django 5.2.4 on 2025-09-28 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recepcao", "0003_populate_attendentes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="visitante",
            name="criado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visitantes_criados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
    ]
