# Generated by Django 5.2.4 on 2025-10-07 14:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Historico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("CRIAR", "Criar"),
                            ("EDITAR", "Editar"),
                            ("EXCLUIR", "Excluir"),
                            ("VISUALIZAR", "Visualizar"),
                            ("ENFILEIRAR", "Enfileirar"),
                            ("INICIAR_ATENDIMENTO", "Iniciar Atendimento"),
                            ("CONCLUIR_ATENDIMENTO", "Concluir Atendimento"),
                            ("CANCELAR_ATENDIMENTO", "Cancelar Atendimento"),
                        ],
                        max_length=50,
                        verbose_name="Ação",
                    ),
                ),
                (
                    "tipo_objeto",
                    models.CharField(
                        choices=[
                            ("COLABORADOR", "Colaborador"),
                            ("CONVIDADO", "Convidado"),
                            ("ATENDIMENTO", "Atendimento"),
                            ("VISITANTE", "Visitante"),
                            ("USUARIO", "Usuário"),
                            ("SISTEMA", "Sistema"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Objeto",
                    ),
                ),
                (
                    "objeto_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID do Objeto"
                    ),
                ),
                (
                    "objeto_nome",
                    models.CharField(max_length=255, verbose_name="Nome do Objeto"),
                ),
                (
                    "descricao",
                    models.TextField(
                        help_text="Descrição detalhada da ação realizada",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "detalhes_antes",
                    models.JSONField(
                        blank=True,
                        help_text="Estado do objeto antes da ação (para edições)",
                        null=True,
                        verbose_name="Detalhes Antes",
                    ),
                ),
                (
                    "detalhes_depois",
                    models.JSONField(
                        blank=True,
                        help_text="Estado do objeto depois da ação",
                        null=True,
                        verbose_name="Detalhes Depois",
                    ),
                ),
                (
                    "data_hora",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Data e Hora"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereço IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histórico",
                "verbose_name_plural": "Históricos",
                "ordering": ["-data_hora"],
                "indexes": [
                    models.Index(
                        fields=["-data_hora"], name="historico_h_data_ho_54686a_idx"
                    ),
                    models.Index(
                        fields=["tipo_objeto", "acao"],
                        name="historico_h_tipo_ob_ded1b3_idx",
                    ),
                    models.Index(
                        fields=["usuario", "-data_hora"],
                        name="historico_h_usuario_84c773_idx",
                    ),
                    models.Index(
                        fields=["objeto_id", "tipo_objeto"],
                        name="historico_h_objeto__a30e7c_idx",
                    ),
                ],
            },
        ),
    ]
