# Generated by Django 5.2.4 on 2026-05-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("historico", "0002_alter_historico_acao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historico",
            name="acao",
            field=models.CharField(
                choices=[
                    ("CRIAR", "Criar"),
                    ("EDITAR", "Editar"),
                    ("EXCLUIR", "Excluir"),
                    ("VISUALIZAR", "Visualizar"),
                    ("ENFILEIRAR", "Enfileirar"),
                    ("INICIAR_ATENDIMENTO", "Iniciar Atendimento"),
                    ("CONCLUIR_ATENDIMENTO", "Concluir Atendimento"),
                    ("CANCELAR_ATENDIMENTO", "Cancelar Atendimento"),
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("RESET", "Reset"),
                ],
                max_length=50,
                verbose_name="Ação",
            ),
        ),
    ]
