# Generated by Django 5.2.4 on 2026-05-13 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colaboradores", "0006_alter_colaborador_tipo"),
        ("convidados", "0003_convidado_cadastrado_por_alter_convidado_colaborador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convidado",
            name="colaborador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="convidados",
                to="colaboradores.colaborador",
            ),
        ),
    ]
