# Generated by Django 5.2.4 on 2026-06-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("convidados", "0004_alter_convidado_colaborador"),
    ]

    operations = [
        migrations.AddField(
            model_name="convidado",
            name="endereco",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Endereço"
            ),
        ),
    ]
