# Generated by Django 5.2.4 on 2026-05-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profiles", "0003_usersession"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="acesso_aniversariantes",
            field=models.BooleanField(
                default=False, verbose_name="Acesso a Aniversariantes"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="acesso_historico",
            field=models.BooleanField(default=False, verbose_name="Acesso a Histórico"),
        ),
        migrations.AddField(
            model_name="profile",
            name="acesso_mensagens",
            field=models.BooleanField(default=False, verbose_name="Acesso a Mensagens"),
        ),
    ]
