# ruff: noqa: RUF012
# Generated by Django 5.2.4 on 2026-06-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profiles", "0004_profile_acesso_aniversariantes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="force_password_change",
            field=models.BooleanField(
                default=False,
                help_text="Se ativo, redirecionado para redefinir senha ao login",
                verbose_name="Forçar troca de senha no próximo login",
            ),
        ),
    ]
